//
// Created by tyll on 2022-09-11.
//

#ifndef SGLOGGER_ELMATCOMMANDS_H
#define SGLOGGER_ELMATCOMMANDS_H

namespace core { namespace can { namespace elm {
    enum ElmOpCode {
        ELM_CONF_REPEAT_LAST,
        ELM_CONF_SET_ALL_TO_DEFAULT,
        ELM_CONF_ECHO_OFF,
        ELM_CONF_ECHO_ON,
        ELM_CONF_FORGET_EVENTS,
        ELM_CONF_PRINT_VERSION_ID,
        ELM_CONF_LINEFEED_OFF,
        ELM_CONF_LINEFEED_ON,
        ELM_CONF_WARM_START,
        ELM_CONF_RESET_ALL,
        ELM_CONF_PRINT_DEVICE_DESCRIPTION,
        ELM_CONF_PRINT_DEVICE_ID,
        ELM_CONF_STORE_DEVICE_ID,
        ELM_CAN_CONFIRMATION_OFF,
        ELM_CAN_CONFIRMATION_ON,
        ELM_CAN_AUTOMATIC_FORMATTING_OFF,
        ELM_CAN_AUTOMATIC_FORMATTING_ON,
        ELM_CAN_SET_ID_FILTER,
        ELM_CAN_FLOW_CONTROL_OFF,
        ELM_CAN_FLOW_CONTROL_ON,
        ELM_CAN_CAN_STATUS,
        ELM_CAN_SILENT_OFF,
        ELM_CAN_SILENT_ON,
        ELM_CAN_SET_TIMER_MULTIPLIER1,
        ELM_CAN_SET_TIMER_MULTIPLIER5,
        ELM_CAN_DLC_OFF,
        ELM_CAN_DLC_ON,
        ELM_CAN_SET_FLOW_CONTROL_MODE,
        ELM_CAN_SEND_REQUEST_TO_RESPOND
    };
}}}

#endif //SGLOGGER_ELMATCOMMANDS_H
